### ISSUE TITLE
Hit a wall with the static file to HLS feature

### ISSUE THREAD

**Issue by cairobraga** [Zibbp/Radium#26]
I'm running Radium alongside nginx-rtmp-hls on Docker and followed the instructions on this project's wiki, but I cannot figure out for the life of me what kind of static file can be served to Radium, taking as it only accepts sources ending with m3u8 file extension and on the wiki there is mention of "if you wanna stream the MKV file directly, do this". Can the dev clarify this, please? I'm sorry if this is the wrong place to ask for this kind of info, but I'm trying really hard to make Radium work for me. Thanks in advance!

**Comment by Zibbp** [comment]
Are you trying to stream a video file (mp4, mkv, etc)? If so, it needs to be converted into HLS format. This can be done in two ways. The first would be to convert it using rtmp, instructions can be found on the [wiki page](https://github.com/Zibbp/Radium/wiki/Video-to-HLS). The second way would be streaming the file instead of converting it. This can be done with OBS and uses the nginx-rtmp-hls container.

**Comment by cairobraga** [comment]
@Zibbp that's what wasn't clear to me: the need to convert any video file to HLS before serving it as a static file. may I suggest to make this point clearer on the wiki? since the example you give says ".../static/MYFILE" without indication it needs to be a m3u8 HLS file, I read it as if it was possible to serve any kind of static video file and kept going back and forth between the "RTMP to HLS" and "Video to HLS" pages, scratching my head on why it wasn't working, lol. thank you for the quick reply and keep up the good work!

**Comment by Zibbp** [comment]
I will update the wiki to make it more clear. Thanks for pointing it out.
